export const configuration = () => ({
  NODE_ENV: process.env.NODE_ENV,
  port: parseInt(process.env.PORT, 10) || 8080,
  database: {
    tag: process.env.DB_TAG,
    url: process.env.DB_URL,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
  },
  jwt: {
    secret: process.env.JWT_SECRET,
    expiresIn: process.env.JWT_EXPIRE_IN,
    expiresInMs: process.env.JWT_EXPIRE_IN_MS,
    refresh_secret: process.env.JWT_REFRESH_SECRET,
    refresh_expiresIn: process.env.JWT_REFRESH_EXPIRE_IN,
    refresh_expiresInMs: process.env.JWT_REFRESH_EXPIRE_IN_MS,
  },
  geocoder_api_key: process.env.GEOCODER_PROVIDER_API_KEY,
  r2: {
    access_key: process.env.R2_ACCESS_KEY_ID,
    secret_access_key: process.env.R2_SECRET_ACCESS_KEY_ID,
    endpoint: process.env.R2_ENDPOINT,
    region: process.env.R2_REGION,
    bucket: process.env.R2_BUCKET,
    public_url: process.env.R2_PUBLIC_URL,
  },
});
